# Generated by Django 3.2.9 on 2021-12-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_added_at',
            field=models.CharField(max_length=240),
        ),
    ]
