# Generated by Django 3.2.9 on 2021-12-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_recipe_recipe_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
