# Generated by Django 3.1.7 on 2021-12-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211203_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='recipe_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
